### ISSUE TITLE
Please implement one of these 3 ideas to quickly paste all direct links at once to clipboard

### ISSUE THREAD

**Issue by atereou** [yasirkula/DownloadLinkGeneratorForGoogleDrive#10]
Could you perhaps implement one of these ideas?

Any of these features could be a quick way to paste all direct links directly to clipboard:

- button/clickable link to paste all direct links at once to clipboard
or
- button/clickable link(as toggle switch perhaps for hide/show) to hide all file names + any other text -
except the direct links, so you could select all direct links with only the keyboard (CTRL+A)
or
- simply add some space below the file names/direct links list and show a second list there with only the direct links
(in this case list all links as plain text, since the active links are already available)

rgds atereou

**Comment by yasirkula** [comment]
Direct links' urls don't give any hint about the file, it consists of random letters and numbers. In your use-case, how will these links be useful on their own; you don't know which url points to which file?

**Comment by atereou** [comment]
I need to prepare a lot of files for my upcoming mobile app projects as downloadable assets.
I usually achieve my desired file order when I place them in folders and sort them by creation date. Then I use an external Drive file upload service that will temporarily preserve order of my uploaded files(Drive reverts everything back to its own file order structure very soon which would destroy order, but there would be enough time to grab the direct links with your DownloadLinkGenerator first).
At this point any option for sending all direct links at once to clipboard would be useful, because then I could easily create .txt files with these links included and run my own tool to generate a list of my files in the folders - with this result for each list line:
"file name,file size,download link"
"file name,file size,download link"
 ... and so on
 This will be the (encrypted) string info in my own online assets scan and download routine that I developed for new app releases.

**Comment by yasirkula** [comment]
This sounds too risky. What if the output of DownloadLinkGenerator doesn't follow your file order? In this case, files will have the wrong download urls. I don't think I want to implement this feature.

You can split filenames and links using a Drive spreadsheet, though. Simply paste the raw output to spreadsheet, select all cells, hit _Data-Split text to columns_ and select _Space_ Separator.

**Comment by atereou** [comment]
OK your idea has convinced me.
Based on this idea I implemented a simple word removal option in my string parsing tool and now everything works as intended.
For the quick direct download link generation part your tool is very helpful.
Thanks for your replies here.
