### ISSUE TITLE
SpreadSheet

### ISSUE THREAD

**Issue by Michaelmeissner1997** [yasirkula/DownloadLinkGeneratorForGoogleDrive#5]
can you make it so it will create a spreadsheet in that folder 
thankyou

**Comment by 21219172** [comment]
Dear Micheal,



I am pretty inexperienced with these things. I can possibly make a hex.
folder, for you, in the future, if it can help you.

But, in my beginning stages, of learning of these sorts of things, can you
reply with, ' a teacher's explanation ',

in why are you asking, this question of myself.


 sincerely,
 blair beekman





____________________________________________________________
_______________________________________________________________________




On Sat, Aug 18, 2018 at 1:24 PM, Michaelmeissner1997 <
notifications@github.com> wrote:


can you make it so it will create a spreadsheet in that folder

**Comment by yasirkula** [comment]
For now, here's a workaround for this issue:

- create a new Google Sheet in your Drive
- copy&paste the output of Download Link Generator to the A1 cell (it will automatically put each line to a different row)
- select C1 and insert `=LEFT(A1,FIND("~~~~~",SUBSTITUTE(A1," ","~~~~~",LEN(A1)-LEN(SUBSTITUTE(A1," ","")))))` next to the _fx_ line above ([credit](https://superuser.com/questions/987648/split-excel-cell-by-last-delimiter-and-get-text-to-left))
- select D1 and insert `=MID(A1,FIND("~~~~~",SUBSTITUTE(A1," ","~~~~~",LEN(A1)-LEN(SUBSTITUTE(A1," ",""))))+1,LEN(A1))` next to the _fx_ line above ([credit](https://superuser.com/questions/986084/split-excel-cell-by-last-delimiter))
- select C1 and D1 cells, drag the blue square at the bottom right corner of the selection and drop it at the row the download links end
- now select the populated C and D columns, copy them, right click a blank cell in your sheet and select `Paste special-Paste values only`
- enjoy the results!
