### ISSUE TITLE
how use it on my website

### ISSUE THREAD

**Issue by immoIT** [yasirkula/DownloadLinkGeneratorForGoogleDrive#8]
i install it on my website but not working

**Comment by yasirkula** [comment]
I've put the source code here for reference. You need to either [use this Drive Add-on](https://gsuite.google.com/marketplace/app/download_link_generator_for_drive/631283629814) or create your own Drive Add-on and write your code similar to mine. But creating a Drive Add-on requires numerous configuration steps, so it may not be feasible for you.

**Comment by immoIT** [comment]
so tell me required additional files for that

**Comment by yasirkula** [comment]
It involves more steps. You should check out the official documentation: https://developers.google.com/drive/api/v3/about-sdk

**Comment by yasirkula** [comment]
I've updated README to clarify things.
