### ISSUE TITLE
Stuck on "generating download link(s), please wait..."

### ISSUE THREAD

**Issue by AbdelH2O** [yasirkula/DownloadLinkGeneratorForGoogleDrive#9]
I used the code on my website and my own CLIENT_ID, but it gets stuck on "generating download link(s), please wait...", but I don't know where to go from here.
Any help would be much appreciated.

**Comment by yasirkula** [comment]
I'm guessing that you've already created a project on Google Cloud Console, configured it and added your app to Drive's "Open with" list. I'd recommend you to open your browser's Developer Console and check for error messages there.

**Comment by AbdelH2O** [comment]
Thanks for your help!

**Comment by AbdelH2O** [comment]
I created my own version using Flask in Python.

**Comment by yasirkula** [comment]
Happy to hear that :)
